version: "2.16"

services:
  db:
    image: mysql:8.0.32
    container_name: marketpedia_db
    restart: always
    environment:
      - MYSQL_DATABASE=marketpedia_db
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
     - db:/var/lib/mysql

volumes:
  db:
    driver: local

networks:
  db:
    driver: bridge